home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('menu/',views.MenuPage.as_view(),name='menu'),
    path('menu/<int:pk>/',views.MenuFilteredPage.as_view(),name='menu_filtered'),
]

menu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
]

if settings.DEBUG:  
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin




#abstract user created

class UserManager(BaseUserManager):
    def create_user(self,number,password):
        if not number:
            raise ValueError('Number Is Not There !')
        user = self.model(number=number)
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,number,password):
        user = self.create_user(number,password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser,PermissionsMixin):
    number = models.CharField(max_length=11,unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    USERNAME_FIELD = 'number'
    objects = UserManager()

    def __str__(self):
        return f"{self.number} - {self.is_superuser}"

home/models.py
from django.db import models


#Category and Foond_and Drink model created for admin of the site to upload the products

class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title
    
class Food_And_Drinks(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='cat')
    name = models.CharField(max_length=50)
    pic = models.ImageField(upload_to='product/')
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render,get_object_or_404
from django.views import View
from django.conf import settings
from .models import Food_And_Drinks,Category


# only shows a simple page for the user to enter the menu

class HomePage(View):
    template_name = 'home/start.html'
    def get(self,request):
        return render(request,self.template_name,{'MU':settings.MEDIA_URL})
# -------------------------------


# shows the menu, unfiltered. shows all of the products in data base.

class MenuPage(View):
    template_name = 'home/menu.html'
    def get(self,request):
        CAT = Category.objects.all().order_by('-id')
        FAD = Food_And_Drinks.objects.all()
        return render(request,self.template_name,{'MU':settings.MEDIA_URL,'CAT':CAT,'FAD':FAD})
# -------------------------------


# this view will handle the filter that user selected. (only one filter)

class MenuFilteredPage(View):
    template_name = 'home/menu.html'
    def get(self,request,*args,**kwargs):
        cat_pk = kwargs['pk']
        cat  = get_object_or_404(Category,pk=cat_pk)
        CAT = Category.objects.all().order_by('-id')
        FAD = Food_And_Drinks.objects.filter(category=cat)
        return render(request,self.template_name,{'MU':settings.MEDIA_URL,'CAT':CAT,'FAD':FAD,'cat_pk':cat_pk})
# -------------------------------

home/templates/home/menu.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}menu{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/css/menu.css' %}">
    <link rel="icon" href="{{MU}}img/Group 1.svg" type="image/svg/png">
{% endblock %}
{% block body %}
<header class="header">
    <div class="header-wrp">
        <h1 class="header-txt">sefr coffee</h1>
        <!-- <h1 class="header-txt">صفر کافه</h1> -->
        <div class="header-icon">
            <img src="{{MU}}img/Group 2.svg" class="header-icon__img" alt="coffee-icon">
        </div>
    </div>
</header>
<!-- <section    class="categorie">
    <div class="categorie-wrp">
        <a href="#" class="categorie__items categorie__items--active">All</a>
        <a href="#" class="categorie__items">Hot coffee</a>
        <a href="#" class="categorie__items">ice coffee</a>
        <a href="#" class="categorie__items">Hot drink</a>
    </div>
</section> -->
<section    class="categorie">
    <div class="categorie-wrp">
        {% for c in CAT %}
        <a href="{% url 'home:menu_filtered' c.pk %}" class="categorie__items {% if cat_pk is c.pk %}categorie__items--active{% endif %}">{{c.title}}</a>
        {% endfor %}
        <a href="{% url 'home:menu' %}" class="categorie__items {% if not cat_pk %}categorie__items--active{% endif %}">همه</a>
    </div>
</section>

<section class="menu">
    <div class="menu-wrp">
        {% for f in FAD %}
        <div class="menu-item">
            <img src="{{f.pic.url}}" alt="{{f.name}}" class="menu-items__img">
            <span class="menu-item__name">{{f.name}}</span>
            <span class="menu-item__price">{{f.price}}</span>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

home/templates/home/start.html
{% extends 'base.html' %}
{% load static %}
{% block title %}sefer coffee{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/css/start.css' %}">
    <link rel="icon" href="{{MU}}img/Group 1.svg" type="image/svg/png">
{% endblock %}
{% block body %}
    <div class="wrapper fade-up" data-aos="fade-up"
     data-aos-duration="3000">
      <div class="wrpper-content">
        <img src="{{MU}}img/Group 1.svg" alt="" class="wrapper-content__img">
        <span class="wrapper-content__txt">sefr coffee</span>
    </div>
        <a href="{% url 'home:menu' %}" class="wrapper-btn "   >مشاهده منو</a>

    
    </div>
    <div class="shap-1 fade-up-right"></div>
        <div class="shap-2"></div>

        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        <script> 
  AOS.init(
    
  );
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>